//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalji
    {
        public int DetaljiID { get; set; }
        public int Narudzba { get; set; }
        public int Proizvod { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Narudzbe Narudzbe { get; set; }
        public virtual Proizvod Proizvod1 { get; set; }
    }
}
