//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class zaraEntities : DbContext
    {
        public zaraEntities()
            : base("name=zaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boja> Boja { get; set; }
        public virtual DbSet<Detalji> Detalji { get; set; }
        public virtual DbSet<Kategorije> Kategorije { get; set; }
        public virtual DbSet<Kupci> Kupci { get; set; }
        public virtual DbSet<Narudzbe> Narudzbe { get; set; }
        public virtual DbSet<Proizvod> Proizvod { get; set; }
        public virtual DbSet<StatusNarudzbe> StatusNarudzbe { get; set; }
        public virtual DbSet<Velicina> Velicina { get; set; }
    
        public virtual ObjectResult<Kategorije> zara_Kategorije_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kategorije>("zara_Kategorije_SelectAll");
        }
    
        public virtual ObjectResult<Kategorije> zara_Kategorije_SelectAll(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kategorije>("zara_Kategorije_SelectAll", mergeOption);
        }
    
        public virtual ObjectResult<zara_Proizvodi_Select_Result> zara_Proizvodi_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zara_Proizvodi_Select_Result>("zara_Proizvodi_Select");
        }
    
        public virtual ObjectResult<zara_Kategorija_PretragaByKategorija_Result> zara_Kategorija_PretragaByKategorija(Nullable<int> kategorija)
        {
            var kategorijaParameter = kategorija.HasValue ?
                new ObjectParameter("Kategorija", kategorija) :
                new ObjectParameter("Kategorija", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zara_Kategorija_PretragaByKategorija_Result>("zara_Kategorija_PretragaByKategorija", kategorijaParameter);
        }
    
        public virtual ObjectResult<GridDetalji_Result> GridDetalji(Nullable<int> narudzbeID)
        {
            var narudzbeIDParameter = narudzbeID.HasValue ?
                new ObjectParameter("NarudzbeID", narudzbeID) :
                new ObjectParameter("NarudzbeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GridDetalji_Result>("GridDetalji", narudzbeIDParameter);
        }
    
        public virtual ObjectResult<GridNarudzbe_Result> GridNarudzbe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GridNarudzbe_Result>("GridNarudzbe");
        }
    
        public virtual ObjectResult<DetaljiByID_Result> DetaljiByID(Nullable<int> detaljiID)
        {
            var detaljiIDParameter = detaljiID.HasValue ?
                new ObjectParameter("DetaljiID", detaljiID) :
                new ObjectParameter("DetaljiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetaljiByID_Result>("DetaljiByID", detaljiIDParameter);
        }
    
        public virtual int UpdateKupci(Nullable<int> kupciID, string korisnickoIme, string lozinka, string ime, string prezime, string adresa, string dodatneInformacije, Nullable<int> postanskiBroj, string grad, string regija, string kontaktTelefon, Nullable<bool> aktivnost)
        {
            var kupciIDParameter = kupciID.HasValue ?
                new ObjectParameter("KupciID", kupciID) :
                new ObjectParameter("KupciID", typeof(int));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("Lozinka", lozinka) :
                new ObjectParameter("Lozinka", typeof(string));
    
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var dodatneInformacijeParameter = dodatneInformacije != null ?
                new ObjectParameter("DodatneInformacije", dodatneInformacije) :
                new ObjectParameter("DodatneInformacije", typeof(string));
    
            var postanskiBrojParameter = postanskiBroj.HasValue ?
                new ObjectParameter("PostanskiBroj", postanskiBroj) :
                new ObjectParameter("PostanskiBroj", typeof(int));
    
            var gradParameter = grad != null ?
                new ObjectParameter("Grad", grad) :
                new ObjectParameter("Grad", typeof(string));
    
            var regijaParameter = regija != null ?
                new ObjectParameter("Regija", regija) :
                new ObjectParameter("Regija", typeof(string));
    
            var kontaktTelefonParameter = kontaktTelefon != null ?
                new ObjectParameter("KontaktTelefon", kontaktTelefon) :
                new ObjectParameter("KontaktTelefon", typeof(string));
    
            var aktivnostParameter = aktivnost.HasValue ?
                new ObjectParameter("Aktivnost", aktivnost) :
                new ObjectParameter("Aktivnost", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateKupci", kupciIDParameter, korisnickoImeParameter, lozinkaParameter, imeParameter, prezimeParameter, adresaParameter, dodatneInformacijeParameter, postanskiBrojParameter, gradParameter, regijaParameter, kontaktTelefonParameter, aktivnostParameter);
        }
    
        public virtual ObjectResult<Kupci> getKupcibyID(Nullable<int> kupciID)
        {
            var kupciIDParameter = kupciID.HasValue ?
                new ObjectParameter("KupciID", kupciID) :
                new ObjectParameter("KupciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kupci>("getKupcibyID", kupciIDParameter);
        }
    
        public virtual ObjectResult<Kupci> getKupcibyID(Nullable<int> kupciID, MergeOption mergeOption)
        {
            var kupciIDParameter = kupciID.HasValue ?
                new ObjectParameter("KupciID", kupciID) :
                new ObjectParameter("KupciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kupci>("getKupcibyID", mergeOption, kupciIDParameter);
        }
    
        public virtual ObjectResult<Kupci> KupciGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kupci>("KupciGrid");
        }
    
        public virtual ObjectResult<Kupci> KupciGrid(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kupci>("KupciGrid", mergeOption);
        }
    
        public virtual ObjectResult<PretragaByNaziv_Result> PretragaByNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PretragaByNaziv_Result>("PretragaByNaziv", nazivParameter);
        }
    
        public virtual int KupciInsert(string korisnickoIme, string lozinka, string ime, string prezime, string adresa, string dodatneInformacije, Nullable<int> postanskiBroj, string grad, string regija, string kontaktTelefon, Nullable<bool> aktivnost)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("Lozinka", lozinka) :
                new ObjectParameter("Lozinka", typeof(string));
    
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var dodatneInformacijeParameter = dodatneInformacije != null ?
                new ObjectParameter("DodatneInformacije", dodatneInformacije) :
                new ObjectParameter("DodatneInformacije", typeof(string));
    
            var postanskiBrojParameter = postanskiBroj.HasValue ?
                new ObjectParameter("PostanskiBroj", postanskiBroj) :
                new ObjectParameter("PostanskiBroj", typeof(int));
    
            var gradParameter = grad != null ?
                new ObjectParameter("Grad", grad) :
                new ObjectParameter("Grad", typeof(string));
    
            var regijaParameter = regija != null ?
                new ObjectParameter("Regija", regija) :
                new ObjectParameter("Regija", typeof(string));
    
            var kontaktTelefonParameter = kontaktTelefon != null ?
                new ObjectParameter("KontaktTelefon", kontaktTelefon) :
                new ObjectParameter("KontaktTelefon", typeof(string));
    
            var aktivnostParameter = aktivnost.HasValue ?
                new ObjectParameter("Aktivnost", aktivnost) :
                new ObjectParameter("Aktivnost", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KupciInsert", korisnickoImeParameter, lozinkaParameter, imeParameter, prezimeParameter, adresaParameter, dodatneInformacijeParameter, postanskiBrojParameter, gradParameter, regijaParameter, kontaktTelefonParameter, aktivnostParameter);
        }
    
        public virtual ObjectResult<GridProizvodByProizvodID_Result> GridProizvodByProizvodID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GridProizvodByProizvodID_Result>("GridProizvodByProizvodID", iDParameter);
        }
    
        public virtual ObjectResult<prijava_Kupci_Result> prijava_Kupci(string korinickoIme, string lozinka)
        {
            var korinickoImeParameter = korinickoIme != null ?
                new ObjectParameter("KorinickoIme", korinickoIme) :
                new ObjectParameter("KorinickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("Lozinka", lozinka) :
                new ObjectParameter("Lozinka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prijava_Kupci_Result>("prijava_Kupci", korinickoImeParameter, lozinkaParameter);
        }
    
        public virtual int insertDetalji(Nullable<int> narudzba, Nullable<int> proizvod, Nullable<int> kolicina)
        {
            var narudzbaParameter = narudzba.HasValue ?
                new ObjectParameter("narudzba", narudzba) :
                new ObjectParameter("narudzba", typeof(int));
    
            var proizvodParameter = proizvod.HasValue ?
                new ObjectParameter("proizvod", proizvod) :
                new ObjectParameter("proizvod", typeof(int));
    
            var kolicinaParameter = kolicina.HasValue ?
                new ObjectParameter("kolicina", kolicina) :
                new ObjectParameter("kolicina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertDetalji", narudzbaParameter, proizvodParameter, kolicinaParameter);
        }
    
        public virtual int insertNarudzbe(Nullable<System.DateTime> datum1, Nullable<System.DateTime> datum2, Nullable<int> brojNarudzbe, Nullable<int> kupac, Nullable<int> statusN)
        {
            var datum1Parameter = datum1.HasValue ?
                new ObjectParameter("Datum1", datum1) :
                new ObjectParameter("Datum1", typeof(System.DateTime));
    
            var datum2Parameter = datum2.HasValue ?
                new ObjectParameter("Datum2", datum2) :
                new ObjectParameter("Datum2", typeof(System.DateTime));
    
            var brojNarudzbeParameter = brojNarudzbe.HasValue ?
                new ObjectParameter("BrojNarudzbe", brojNarudzbe) :
                new ObjectParameter("BrojNarudzbe", typeof(int));
    
            var kupacParameter = kupac.HasValue ?
                new ObjectParameter("Kupac", kupac) :
                new ObjectParameter("Kupac", typeof(int));
    
            var statusNParameter = statusN.HasValue ?
                new ObjectParameter("StatusN", statusN) :
                new ObjectParameter("StatusN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertNarudzbe", datum1Parameter, datum2Parameter, brojNarudzbeParameter, kupacParameter, statusNParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> getNaruzdbaID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getNaruzdbaID");
        }
    
        public virtual ObjectResult<Boja> Bojacombo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Boja>("Bojacombo");
        }
    
        public virtual ObjectResult<Boja> Bojacombo(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Boja>("Bojacombo", mergeOption);
        }
    
        public virtual ObjectResult<Kategorije> Kategorijacombo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kategorije>("Kategorijacombo");
        }
    
        public virtual ObjectResult<Kategorije> Kategorijacombo(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kategorije>("Kategorijacombo", mergeOption);
        }
    
        public virtual ObjectResult<Velicina> Velicinacombo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Velicina>("Velicinacombo");
        }
    
        public virtual ObjectResult<Velicina> Velicinacombo(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Velicina>("Velicinacombo", mergeOption);
        }
    
        public virtual int insertProizvoda(string naziv, Nullable<int> kategorija, byte[] slika, Nullable<int> velicina, Nullable<decimal> cijena, Nullable<int> boja, byte[] slikaThumb)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var kategorijaParameter = kategorija.HasValue ?
                new ObjectParameter("Kategorija", kategorija) :
                new ObjectParameter("Kategorija", typeof(int));
    
            var slikaParameter = slika != null ?
                new ObjectParameter("Slika", slika) :
                new ObjectParameter("Slika", typeof(byte[]));
    
            var velicinaParameter = velicina.HasValue ?
                new ObjectParameter("Velicina", velicina) :
                new ObjectParameter("Velicina", typeof(int));
    
            var cijenaParameter = cijena.HasValue ?
                new ObjectParameter("Cijena", cijena) :
                new ObjectParameter("Cijena", typeof(decimal));
    
            var bojaParameter = boja.HasValue ?
                new ObjectParameter("Boja", boja) :
                new ObjectParameter("Boja", typeof(int));
    
            var slikaThumbParameter = slikaThumb != null ?
                new ObjectParameter("SlikaThumb", slikaThumb) :
                new ObjectParameter("SlikaThumb", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertProizvoda", nazivParameter, kategorijaParameter, slikaParameter, velicinaParameter, cijenaParameter, bojaParameter, slikaThumbParameter);
        }
    
        public virtual ObjectResult<Proizvod> UcitajSliku(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proizvod>("UcitajSliku", idParameter);
        }
    
        public virtual ObjectResult<Proizvod> UcitajSliku(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proizvod>("UcitajSliku", mergeOption, idParameter);
        }
    }
}
