//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbe()
        {
            this.Detalji = new HashSet<Detalji>();
        }
    
        public int NarudzbeID { get; set; }
        public Nullable<System.DateTime> DatumNarudzbe { get; set; }
        public Nullable<System.DateTime> DatumIsporuke { get; set; }
        public Nullable<int> BrojNarudzbe { get; set; }
        public int Kupac { get; set; }
        public int StatusNarudzbe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalji> Detalji { get; set; }
        public virtual Kupci Kupci { get; set; }
        public virtual StatusNarudzbe StatusNarudzbe1 { get; set; }
    }
}
