//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.Detalji = new HashSet<Detalji>();
        }
    
        public int ProizvodiID { get; set; }
        public string Naziv { get; set; }
        public int Kategorija { get; set; }
        public byte[] Slika { get; set; }
        public int Velicina { get; set; }
        public decimal Cijena { get; set; }
        public int BojaID { get; set; }
        public byte[] SlikaThumb { get; set; }
    
        public virtual Boja Boja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalji> Detalji { get; set; }
        public virtual Kategorije Kategorije { get; set; }
        public virtual Velicina Velicina1 { get; set; }
    }
}
